kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-db-pvc
  namespace: immich
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi  # Match or be less than the PV's capacity
  volumeName: immich-db-pv  # Bind explicitly to the PV created above
  storageClassName: ''