kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-nfs-library-pvc
  namespace: immich
  labels:
    app: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi  # Match or be less than the PV's capacity
  volumeName: immich-nfs-library-pv  # Bind explicitly to the PV created above
  storageClassName: ''
