apiVersion: v1
kind: Service
metadata:
  name: immich-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 2283
    nodePort: 30112
    protocol: TCP
  selector:
    app: immich-server