argocd-apps:
  applications:
    - name: argocd
      namespace: argocd
      destination:
        namespace: argocd
      project: argocd
      source:
        path: argocd
        repoURL: https://github.com/ceeb0t/kub.git
        targetRevision: HEAD
        helm:
          releaseName: argocd
          valueFiles:
            - values.yaml
      syncPolicy:
        syncOptions:
          - CreateNamespace=false
          - ApplyOutOfSyncOnly=false