apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pluralsite-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ceeb0t/kub.git
    path: Nigel
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      enabled: true
