apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-db-pv
  namespace: immich
  labels:
    app: immich-postgresql
spec:
  capacity:
    storage: 10Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mnt/Cache/immich"  # Static path on the NFS server
    server: 192.168.21.20               # Your NFS server's IP
  persistentVolumeReclaimPolicy: Retain